package callisto

import "config"
import sa "core:container/small_array"
import sdl "vendor:sdl3"
import "core:log"
import "core:strings"
import "core:slice"
import "core:mem"


Resource_Uploader :: struct {
        device         : ^sdl.GPUDevice,
        command_buffer : ^sdl.GPUCommandBuffer,
        copy_pass      : ^sdl.GPUCopyPass,
}

resource_uploader_create :: proc(device: ^sdl.GPUDevice) -> (r: Resource_Uploader, ok: bool) {
        r = Resource_Uploader {
                device = device,
                // other fields populated on begin
        }
        ok = true
        return
}

resource_uploader_destroy :: proc(r: ^Resource_Uploader) { 
        // no-op
}

resource_upload_begin :: proc(r: ^Resource_Uploader) {
        r.command_buffer = sdl.AcquireGPUCommandBuffer(r.device)
        r.copy_pass = sdl.BeginGPUCopyPass(r.command_buffer)
}


// Blocks the current thread until GPU resources are ready to be used.
// If you wish to continue running async, use `resource_upload_end_and_acquire_fence` instead.
resource_upload_end_wait :: proc(r: ^Resource_Uploader) {
        fence := resource_upload_end_and_acquire_fence(r)
        if fence != nil {
                ok := sdl.WaitForGPUFences(r.device, false, &fence, 1)
                if !ok {
                        log.error(sdl.GetError())
                }
                sdl.ReleaseGPUFence(r.device, fence)
        }
}


// Fence must be released when done with it.
resource_upload_end_and_acquire_fence :: proc(r: ^Resource_Uploader) -> ^sdl.GPUFence {
        sdl.EndGPUCopyPass(r.copy_pass)
        fence := sdl.SubmitGPUCommandBufferAndAcquireFence(r.command_buffer)
        if fence == nil {
                log.error(sdl.GetError())
        }
        r.copy_pass = nil
        r.command_buffer = nil

        return fence
}


Shader :: struct {
        gpu_shader: ^sdl.GPUShader,
}

shader_create :: proc(device: ^sdl.GPUDevice, asset: ^Asset_Shader, temp_allocator := context.temp_allocator) -> (shader: Shader, ok: bool) {
        // If this is parsed from cbor this is unnecessary as the decoder appends a 0 byte to text, 
        // however it can't be guaranteed when providing an asset generated by user code.
        entrypoint_c := strings.clone_to_cstring(asset.entrypoint, temp_allocator)
        defer delete(entrypoint_c, temp_allocator)

        // Translate to SDL create info
        create_info := sdl.GPUShaderCreateInfo {
                code_size            = uint(len(asset.code)),
                code                 = raw_data(asset.code),
                entrypoint           = entrypoint_c,
                format               = asset.format,
                stage                = asset.stage,
                num_samplers         = asset.num_samplers,
                num_storage_textures = asset.num_storage_textures,
                num_storage_buffers  = asset.num_storage_buffers,
                num_uniform_buffers  = asset.num_uniform_buffers,

                props                = asset.props,
        }

        shader = Shader {
                gpu_shader = sdl.CreateGPUShader(device, create_info),
        }
        ok = shader.gpu_shader != nil

        return
}


shader_destroy :: proc(device: ^sdl.GPUDevice, shader: ^Shader) {
        sdl.ReleaseGPUShader(device, shader.gpu_shader)
        shader.gpu_shader = nil
}



Texture_Type :: enum {
        Color,
        Normal,
        Linear_Data,
}

Texture :: struct {
        gpu_texture : ^sdl.GPUTexture,
        type        : Texture_Type,
}


Mesh_Renderer :: struct {
        mesh : Mesh,
        materials : sa.Small_Array(config.MAX_SUBMESHES, ^Material),
}


Vertex_Attribute_Slots :: bit_set[Vertex_Attribute_Slot]
Vertex_Attribute_Slot :: enum {
        Position,
        Normal,
        Tangent,
        Tex_Coord_0,
        Color_0,
        // skinning data
}

Mesh :: struct {
        index_buffer  : ^sdl.GPUBuffer, // All submesh index_ and index_shadow_buffers are packed into this buffer
        vertex_buffer : ^sdl.GPUBuffer, // All submesh vertex attributes are packed into this buffer
        submeshes     : []Submesh,
}


Submesh :: struct {
        material_slot_name         : string,
        flags                      : Submesh_Flags,
        index_buffer_offset        : u32,
        index_buffer_len           : u32,
        index_shadow_buffer_offset : u32,
        index_shadow_buffer_len    : u32,

        vertex_buffer_offsets      : [Vertex_Attribute_Slot]u32,
        vertex_buffer_len          : u32,
}

mesh_create :: proc(r: ^Resource_Uploader, asset: ^Asset_Mesh, allocator := context.allocator) -> (mesh: Mesh, ok: bool) {
        // Sum up size of all buffers
        index_buffer_size := 0
        vertex_buffer_size := 0

        mesh.submeshes = make([]Submesh, len(asset.submesh_infos), allocator)

        for info in asset.submesh_infos {
                index_buffer_size  += slice.size(info.index_data)
                index_buffer_size  += slice.size(info.index_shadow_data)
                vertex_buffer_size += slice.size(info.position_data)
                vertex_buffer_size += slice.size(info.normal_data)
                vertex_buffer_size += slice.size(info.tangent_data)
                vertex_buffer_size += slice.size(info.tex_coord_0_data)
                vertex_buffer_size += slice.size(info.color_0_data)
        }

        // Create transfer buffer
        transfer_buffer_info := sdl.GPUTransferBufferCreateInfo {
                usage = .UPLOAD,
                size  = u32(index_buffer_size) + u32(vertex_buffer_size),
        }
        transfer_buffer := sdl.CreateGPUTransferBuffer(r.device, transfer_buffer_info)
        defer sdl.ReleaseGPUTransferBuffer(r.device, transfer_buffer)

       
        // Create GPU buffers
        index_buffer_info := sdl.GPUBufferCreateInfo {
                usage = {.INDEX},
                size  = u32(index_buffer_size),
        }
        mesh.index_buffer = sdl.CreateGPUBuffer(r.device, index_buffer_info)
        
        vertex_buffer_info := sdl.GPUBufferCreateInfo {
                usage = {.VERTEX},
                size  = u32(vertex_buffer_size),
        }
        mesh.vertex_buffer = sdl.CreateGPUBuffer(r.device, vertex_buffer_info)
       

        // Copy data to transfer buffer
        vertex_buffer_cursor   := 0
        index_buffer_cursor    := 0
        mapped := uintptr(sdl.MapGPUTransferBuffer(r.device, transfer_buffer, true))

        // Index buffer pass
        for info, i in asset.submesh_infos {
                submesh := &mesh.submeshes[i]
                submesh.flags = info.flags

                submesh.index_buffer_len = u32(len(info.index_data))
                submesh.index_shadow_buffer_len = u32(len(info.index_shadow_data))
                if .U32_Indices in info.flags {
                        submesh.index_buffer_len /= 2
                        submesh.index_shadow_buffer_len /= 2
                }

                sub_index_size := slice.size(info.index_data)
                mem.copy(rawptr(mapped), raw_data(info.index_data), sub_index_size)
                mapped += uintptr(sub_index_size)
                
                submesh.index_buffer_offset = u32(index_buffer_cursor) // suballocation
                index_buffer_cursor += sub_index_size

                sub_index_shadow_size := slice.size(info.index_shadow_data)
                mem.copy(rawptr(mapped), raw_data(info.index_shadow_data), sub_index_shadow_size)
                mapped += uintptr(sub_index_shadow_size)
                
                submesh.index_shadow_buffer_offset = u32(index_buffer_cursor) // suballocation
                index_buffer_cursor += sub_index_shadow_size
        }

        // Vertex buffer pass
        for info, i in asset.submesh_infos {
                submesh := &mesh.submeshes[i]
                size: int

                // Position
                size = slice.size(info.position_data)
                submesh.vertex_buffer_len = u32(size)
                submesh.vertex_buffer_offsets[.Position] = u32(vertex_buffer_cursor)
                mem.copy(rawptr(mapped), raw_data(info.position_data), size)
                mapped += uintptr(size)
                vertex_buffer_cursor += size
               
                // Normal
                size = slice.size(info.normal_data)
                submesh.vertex_buffer_offsets[.Normal] = u32(vertex_buffer_cursor)
                mem.copy(rawptr(mapped), raw_data(info.normal_data), size)
                mapped += uintptr(size)
                vertex_buffer_cursor += size
                
                // Tangent
                size = slice.size(info.tangent_data)
                submesh.vertex_buffer_offsets[.Tangent] = u32(vertex_buffer_cursor)
                mem.copy(rawptr(mapped), raw_data(info.tangent_data), size)
                mapped += uintptr(size)
                vertex_buffer_cursor += size
                
                // Tex_Coord_0
                size = slice.size(info.tex_coord_0_data)
                submesh.vertex_buffer_offsets[.Tex_Coord_0] = u32(vertex_buffer_cursor)
                mem.copy(rawptr(mapped), raw_data(info.tex_coord_0_data), size)
                mapped += uintptr(size)
                vertex_buffer_cursor += size
                
                // Color_0
                size = slice.size(info.color_0_data)
                submesh.vertex_buffer_offsets[.Color_0] = u32(vertex_buffer_cursor)
                mem.copy(rawptr(mapped), raw_data(info.color_0_data), size)
                mapped += uintptr(size)
                vertex_buffer_cursor += size
        }
        sdl.UnmapGPUTransferBuffer(r.device, transfer_buffer)


        // Upload commands
        index_transfer_src := sdl.GPUTransferBufferLocation {
                transfer_buffer = transfer_buffer,
                offset = 0,
        }
        index_transfer_dst := sdl.GPUBufferRegion {
                buffer = mesh.index_buffer,
                offset = 0,
                size   = u32(index_buffer_size),
        }
        sdl.UploadToGPUBuffer(r.copy_pass, index_transfer_src, index_transfer_dst, false)


        vertex_transfer_src := sdl.GPUTransferBufferLocation {
                transfer_buffer = transfer_buffer,
                offset = u32(index_buffer_size),
        }
        vertex_transfer_dst := sdl.GPUBufferRegion {
                buffer = mesh.vertex_buffer,
                offset = 0,
                size   = u32(vertex_buffer_size),
        }
        
        sdl.UploadToGPUBuffer(r.copy_pass, vertex_transfer_src, vertex_transfer_dst, false)

        return
}


mesh_destroy :: proc(device: ^sdl.GPUDevice, mesh: ^Mesh, allocator := context.allocator) {
        sdl.ReleaseGPUBuffer(device, mesh.index_buffer)
        sdl.ReleaseGPUBuffer(device, mesh.vertex_buffer)
        mesh.index_buffer = nil
        mesh.vertex_buffer = nil

        delete(mesh.submeshes, allocator)
}


Material :: struct {
        vertex_input            : Vertex_Attribute_Slots,
        pipeline                : ^sdl.GPUGraphicsPipeline,
        textures_vertex         : sa.Small_Array(config.MAX_TEXTURES, Texture),
        textures_fragment       : sa.Small_Array(config.MAX_TEXTURES, Texture),
        property_block_vertex   : ^sdl.GPUBuffer,
        property_block_fragment : ^sdl.GPUBuffer,
}


