package imgui

// This is a generated helper file which you can use to know which
// implementations have been compiled into the bindings.

BACKEND_ALLEGRO5_ENABLED :: false
BACKEND_ANDROID_ENABLED :: false
BACKEND_DX9_ENABLED :: false
BACKEND_DX10_ENABLED :: false
BACKEND_DX11_ENABLED :: false
BACKEND_DX12_ENABLED :: false
BACKEND_GLFW_ENABLED :: false
BACKEND_GLUT_ENABLED :: false
BACKEND_METAL_ENABLED :: false
BACKEND_OPENGL2_ENABLED :: false
BACKEND_OPENGL3_ENABLED :: false
BACKEND_OSX_ENABLED :: false
BACKEND_SDL2_ENABLED :: false
BACKEND_SDL3_ENABLED :: true
BACKEND_SDLGPU3_ENABLED :: true
BACKEND_SDLRENDERER2_ENABLED :: false
BACKEND_SDLRENDERER3_ENABLED :: false
BACKEND_VULKAN_ENABLED :: false
BACKEND_WGPU_ENABLED :: false
BACKEND_WIN32_ENABLED :: false
